# GENERAL
scenario: 'cifar100'
use_rand_class_ordering: True
num_workers: 1
backbone: "resnet18_big_t"
use_small_resolution_adj: True
task_incr: True
use_data_aug: "simclr"
optim: "adamW"
lr_decay: 1.0
lr: 0.001
bs: 128
weight_decay: 0.0005
epochs: [1]
skip_initial_eval: True
eval_max_iterations: 0
enable_continual_eval: False
use_lp_eval: ["linear", "knn"]
knn_k: [10]
lp_eval_all: True

# STRATEGY
strategy: "finetune"




  
