# GENERAL
scenario: 'cifar100'
num_experiences: 10
use_rand_class_ordering: True
num_workers: 1
backbone: "resnet18_big_t"
use_small_resolution_adj: True
task_incr: True
use_data_aug: "simclr"
optim: "adamW"
lr: 0.001
bs: 128
weight_decay: 0.0005
epochs: [50]
lp_finetune_epochs: 100
skip_initial_eval: False
eval_max_iterations: 0
knn_k: [1, 10, 50, 200]
lp_eval_all: True

# STRATEGY
strategy: "concat_finetune"
use_lp_eval: ["concat_linear"]
use_concatenated_eval: True 
